// The keyboard shortcut list, shown in the inspector and in Help.

export const SHORTCUTS = [
  ['Arrows, Tab', 'Move the selection'],
  ['Enter, F2', 'Edit the title'],
  ['Esc', 'Cancel editing, leave pick mode'],
  ['Delete', 'Delete the selected item'],
  ['Alt + ↑ ↓', 'Move a dimension'],
  ['Alt + ← →', 'Move a parameter'],
  ['M', 'Move a dimension to the other space'],
  ['1 – 3, 0', 'Problem: set the stage, clear it'],
  ['F', 'Problem: cycle the stage'],
  ['X', 'Problem: mark out of scope'],
  ['1 – 9', 'Solution: toggle pick for O1 – O9'],
  ['Space', 'Pick mode: toggle pick'],
  ['Ctrl + Z', 'Undo'],
  ['Ctrl + Shift + Z', 'Redo'],
  ['Ctrl + S', 'Save'],
  ['I', 'Show / hide the inspector'],
  ['?', 'Help'],
  ['Ctrl + O', 'Open'],
  ['Ctrl + Shift + S', 'Save as'],
  ['Double-click', 'Edit a title'],
  ['Drag', 'Reorder dimensions, parameters and option chips'],
];
